[package]
name = "tree-sitter-stack-graphs"
version = "0.8.2"
description = "Create stack graphs using tree-sitter parsers"
homepage = "https://github.com/github/stack-graphs/tree/main/tree-sitter-stack-graphs"
repository = "https://github.com/github/stack-graphs/"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [
  "GitHub <opensource+stack-graphs@github.com>",
  "Douglas Creager <dcreager@dcreager.net>",
  "Hendrik van Antwerpen <hendrikvanantwerpen@github.com>",
]
edition = "2018"

[lib]
# All of our tests are in the tests/it "integration" test executable.
test = false

[[bin]]
name = "tree-sitter-stack-graphs"
required-features = ["cli"]

[features]
cli = [
  "base64",
  "clap",
  "colored",
  "dialoguer",
  "dirs",
  "env_logger",
  "indoc",
  "pathdiff",
  "serde_json",
  "sha1",
  "stack-graphs/serde",
  "stack-graphs/storage",
  "stack-graphs/visualization",
  "time",
  "tree-sitter-config",
  "tree-sitter-graph/term-colors",
  "walkdir",
]
lsp = [
  "capture-it",
  "crossbeam-channel",
  "tokio",
  "tower-lsp",
]

[dependencies]
anyhow = "1.0.4"
base64 = { version = "0.21", optional = true }
capture-it = { version = "0.3", optional = true }
clap = { version = "4", optional = true, features = ["derive"] }
colored = { version = "2.0", optional = true }
controlled-option = "0.4.1"
crossbeam-channel = { version = "0.5", optional = true }
dialoguer = { version = "0.10", optional = true }
dirs = { version = "5", optional = true }
env_logger = { version = "0.9", optional = true }
indoc = { version = "1.0", optional = true }
itertools = "0.10"
log = "0.4"
lsp-positions = { version="0.3", path="../lsp-positions", features=["tree-sitter"] }
once_cell = "1"
pathdiff = { version = "0.2.1", optional = true }
regex = "1"
rust-ini = "0.18"
serde_json = { version="1.0", optional=true }
sha1 = { version="0.10", optional=true }
stack-graphs = { version="0.13", path="../stack-graphs" }
thiserror = "1.0"
time = { version = "0.3", optional = true }
tokio = { version = "1.26", optional = true, features = ["io-std", "rt", "rt-multi-thread"] }
tower-lsp = { version = "0.19", optional = true }
tree-sitter = "0.22.5" # keep the same minor version as the tree-sitter dependency
                     # of tree-sitter-graph to prevent install problems
tree-sitter-config = { version = "0.22.5", optional = true }
tree-sitter-graph = { git = "https://github.com/quentinLeDilavrec/tree-sitter-graph", rev = "f09e4a7bd49893b3859fd35446a81314968d665b", version = "0.12" }
tree-sitter-loader = "0.22.5"
walkdir = { version = "2.3", optional = true }

[dev-dependencies]
pretty_assertions = "0.7"
tree-sitter-python = "0.21.0"
